# Generated by Django 4.0.4 on 2022-06-20 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_student_email_teacher_email'),
        ('quiz', '0002_alter_quiz_author_alter_quiz_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.teacher'),
        ),
    ]
