# Generated by Django 4.0.4 on 2022-05-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_alter_student_lectures_attended_alter_student_prn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
